### PR TITLE
[ADD] connector_taxjar: Initial Release

### PR DESCRIPTION
**Pull request by lasley**
Initial release currently supports:
* Import of TaxJar Product Tax codes as Odoo `account.tax` records
* Import of TaxJar Nexus Addresses as Odoo `account.fiscal.position`
  records.
* Tax Rate Estimation on Sales
  * In order to reduce API calls, tax rates are only gathered for sales that
    are shipping to zones covered by configured Nexus addresses.

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello @lasley I'm very interested in the design of this in order to catch ideas for the Brazilian localizations where the tax system is extremely complex, so I pretend to review this...

**Comment by rvalyi** [comment]
@lasley so for Brazil, we could use a similar approach. In fact so far we built the https://github.com/OCA/account-fiscal-rule project and spend days filling hundreds of rules to get the proper fiscal positions for a given ERP project. But this is doesn't scale because this is very complex to set up and keep up to date. So for a SaaS perspective we could be tempted to use a similar connector system or even implement a tax engine inside Odoo that would populate all possible taxes and select the right applicable one.

The point is, in either cases, if we keep the Odoo tax model, we would have hundreds of thousands if not millions of tax rates then in a typical Odoo database for Brazil if all taxes were to be pre-loaded in the database.

An alternative would be to have a different tax model with a variable rate that would instead be attached to the sale order line or invoice line (here we should have this rate on the line for fiscal reporting anyway). Then the tax computation would get this rate dynamically for the specific sale/invoice line we are dealing with.

What is your opinion about such system? Could this be used for the USA?
cc @renatonlima

**Comment by lasley** [comment]
@rvalyi - Your proposal is basically what I did here, although I tried to use as much of the existing methodologies as possible - specifically leveraging the `account_tax_python` module for the variable rates.

There are only 14 total tax categories (`account.tax`) linked to this connector, which differentiate the categories for taxation - such as clothing items or services. 

We then used the fiscal positions to represent Nexus regions, which are the actual locations in which taxation applies. 

I'm not using the fiscal positions in the way they typically are though. Instead- if an `account.tax` that is linked to this connector is selected on the product that is being purchased, the fiscal positions will be queried for the line item and the partner purchasing it. If the partner falls within the fiscal position, the API will be queried for the line item rate. 

The above means that fiscal position itself is not actually being applied anywhere (such as the partner or sale order). 

Once export starts coming into play (create & refund transactions), the fiscal position will be applied to the sale order. It's just virtual right now because it's all quoting at the moment.

**Comment by lasley** [comment]
It's probably worth noting - the current design hits the remote API quite often because it is performing rate quotes live as the sale is updating. With TaxJar this can be an issue, because you are billed based on hits to the API.

My circumvention here is to add the ability to disable live rate quotes. This will force rate generation for the actual transaction only (confirm sale), instead of every time the sale is updated.

**Comment by lasley** [comment]
@rvalyi - In Brazil, do you have to consider taxes on records that are not of the following models?
* `account.invoice`
* `sale.order`
* `purchase.order`

**Pull request merged**
